# Generated by Django 2.2.4 on 2019-12-23 15:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191215_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('ORTHOMOSAIC', 'Orthomosaic'), ('SHAPEFILE', 'Shapefile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='camera',
            field=models.CharField(choices=[('REDEDGE', 'Micasense RedEdge'), ('RGB', 'RGB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for images'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DEMO_USER', 'DemoUser'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('ADMIN', 'Admin')], default=core.models.UserType('DemoUser'), max_length=20),
        ),
    ]
