# Generated by Django 3.0 on 2019-12-26 13:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191223_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for images'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled')], default=core.models.FlightState['WAITING'], max_length=10),
        ),
    ]
