# Generated by Django 3.0 on 2019-12-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191226_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='processing_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
