# Generated by Django 3.0.1 on 2019-12-29 23:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_flight_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for images'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default=core.models.FlightState['WAITING'], max_length=10),
        ),
    ]
