# Generated by Django 3.0.1 on 2020-01-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191229_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='demo_flights',
            field=models.ManyToManyField(related_name='demo_users', to='core.Flight'),
        ),
    ]
