# Generated by Django 3.0.1 on 2020-01-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200105_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for images'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default='WAITING', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DEMO_USER', 'DemoUser'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('ADMIN', 'Admin')], default='DEMO_USER', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique name on same user'),
        ),
    ]
