# Generated by Django 3.0.1 on 2020-02-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200127_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoproject',
            name='artifacts',
            field=models.ManyToManyField(blank=True, related_name='demo_projects', to='core.Artifact'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='artifacts',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to='core.Artifact'),
        ),
    ]
