# Generated by Django 3.0.1 on 2020-02-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200207_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='must_create_workspace',
            field=models.BooleanField(default=True),
        ),
    ]
