# Generated by Django 3.0.1 on 2020-03-07 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userproject_must_create_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='demoproject',
            name='artifacts',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='artifacts',
        ),
        migrations.AddField(
            model_name='artifact',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.UserProject'),
        ),
    ]
