# Generated by Django 3.0.1 on 2020-03-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_artifact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='title',
            field=models.CharField(default='dummy', max_length=256),
            preserve_default=False,
        ),
    ]
