# Generated by Django 3.0.1 on 2020-06-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_artifact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('ORTHOMOSAIC', 'Orthomosaic'), ('SHAPEFILE', 'Shapefile'), ('INDEX', 'Index')], max_length=20),
        ),
    ]
