# Generated by Django 3.0.1 on 2020-08-12 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200621_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demo_projects',
            field=models.ManyToManyField(related_name='demo_users', to='core.UserProject'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DemoProject',
        ),
    ]
