# Generated by Django 3.0 on 2020-08-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200811_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('USER_NAME', 'UserName'), ('IP', 'Ip'), ('EMAIL', 'Email'), ('DOMAIN', 'Domain')], max_length=20)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('value', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
