# Generated by Django 3.0.1 on 2021-03-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_blockcriteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='multispectral_processing',
        ),
    ]
