# Generated by Django 3.0.1 on 2021-03-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_flight_multispectral_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='num_images',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
