# Generated by Django 3.0.1 on 2021-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_flight_num_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='used_space',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
