# Generated by Django 3.0.1 on 2021-03-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_flight_used_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_space',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
