# Generated by Django 3.0.1 on 2021-03-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_used_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maximum_space',
            field=models.PositiveIntegerField(default=47185920),
        ),
        migrations.AddField(
            model_name='userproject',
            name='used_space',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
