# Generated by Django 3.0.1 on 2021-04-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210331_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_month_quota',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='user',
            name='remaining_images',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
