name: End-to-end tests with Cypress

on: [push]

jobs:        
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: 'http://localhost:8001'
          wait-on-timeout: 120
          record: true
          browser: chrome
          headless: true
          parallel: true
          working-directory: ./frontend
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
