name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.5.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install mysql_config
        run: sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test
